namespace QST.MicroERP.Core.Enums
{
    public enum TableNames
    {
        ACC_Voucher,
        ACC_VoucherDetail,
        ACC_VoucherType,

        ATT_Attendance,

        CTL_Clients,
        CTL_Customer,
        CTL_EnumLine,
        CTL_Enums,
        CTL_Item,
        CTL_LogEvent,
        CTL_SMTPCredentials,
        CTL_Supplier,
        CTL_UOMConversion,

        NTF_NotificationLog,
        NTF_NotificationTemplate,

        PMS_Appointment,
        PMS_Doctor,
        PMS_Patient,
        PMS_PatientReport,
        PMS_Prescription,
        PMS_PtExtraFieldsData,
        PMS_RxEdextraFieldsData,
        PMS_RxMedicine,
        PMS_Staff,

        PUR_Purchase,
        PUR_PurchaseLine,

        SAL_DC,
        SAL_DCDetail,
        SAL_DocumentExtras,
        SAL_ItemUOM,
        SAL_ItemVariants,
        SAL_ProductAttrib,
        SAL_ProductTaxes,
        SAL_Sale,
        SAL_SaleLine,
        SAL_SaleStock,
        SAL_StockTransfer,
        SAL_StockTransferLine,

        SCH_Schedule,
        SCH_ScheduleDay,
        SCH_ScheduleDayEvent,

        SEC_Permission,

        TMS_Attachments,
        TMS_Task,
        TMS_TaskComment,
        TMS_UserTask,

        VOC_Vocabulary,
        VOC_UserVocabulary,

        dcline,
        permissions,
        feature,
        course,
        UserTargets,
        City, 
        client,
        sch, 
        notification_log,
        notificationtemplate,
        schLine,
        CityStudent,
        Student,
        useraccount,
        ScheduleDaysEvents,
        user,
        coursedetail,
        courseschedule,
        inquiry,
        classtiming,
        topic,
        lecture,
        assignTask,
        student,
        Tasks,
        assignclass,
        branchschool,
        feepaymentschool,
        feetypeschool,
        guardianschool,
        studentschool,
        school,
        Vocabulary,
        attributes,
        attributevalues,
    }
}
