export enum EnumTypes {
    WeekDays = 1101,
    Entities,
    ScheduleType,
    WorkingType,
    EventType,
    Locations,
    TaskStatuses,
    Priorities,
    TaskModules,
    TaskClaims,
    Reasons,
    Novels,
    Chapters,
    VocabDifficuiltyLevels,
}